### ISSUE TITLE
運用方針を決める

### ISSUE THREAD

**Issue by MrBearing** [EnyaKitakagaya/EnyaKitakagaya.github.io#1]

**Comment by ToruHagihara** [comment]
運用設計に当たって、何のためにGitHubを使うか意識しないと管理が大変なだけになりそうです。
以下設計メモです。 「目的」を意識共有してブレなければ上手くいく予感。
「目的」について思っていたのと違う点があれば以下コメント下さい。

---
- 目的にしたいこと
  -- WSのクオリティアップ　
  -- WS配布物の管理を楽にする
  -- メンバーの共同作業を楽にする
- GitHubを立ち上げる上で大事にしたい点
  -- いきなり膨大な機能を使いこなせないので、目的ごとに運用設計を分割して段階的に導入した方が良い
  -- 会計資料など載せたくない内部情報もある。何を管理・公開していくか決め事が大事
  -- 間違いも含め全てが記録に残る・全てがオープンになることに注意。
  -- ソース管理やfacebookとの連携をどうするかなど、 やり方が変わる作業と変わらない作業の整理が大事。

**Comment by noraneko77** [comment]
・ワークショップを行った！！というだけではなく、今後の課題を反映させてゆきたい。
・ワークショップ資料（PDF）の公開。

**Comment by ToruHagihara** [comment]
@noraneko77 今後の課題というと例えばコレというものはどんなものでしょう？

**Comment by MrBearing** [comment]
日本語がおかしかったので、修正しました。
あと、ページの作成は別Issueにしたほうがすっきりしそうなので分離

**Comment by ToruHagihara** [comment]
@noraneko77 あとPDFである事にこだわりがなければ、元の形式で公開する方式や他の作り方で公開する方式でも大丈夫ですかね？
（PDFは一度作ると編集するのが難しいので。。。）
※まず最初はこれまでの作り方に沿って作ったPDFをそのまま公開とかでもアリかと思っています。

**Comment by ToruHagihara** [comment]
メモ：１リポジトリを何度もバージョンアップして開催することを考えておくと良い。
リリース機能を使って開催ごとに内容を記録すると良いかも。
