### ISSUE TITLE
Githubの基礎的な使い方をまとめたページを作る

### ISSUE THREAD

**Issue by MrBearing** [EnyaKitakagaya/EnyaKitakagaya.github.io#2]
Githubの使い方、特にワークショップをするときに必要になることを順次まとめてく

**Comment by ToruHagihara** [comment]
内部向けと参加者向けを上手く切り離したサイト構造を考えたいですね。

**Comment by MrBearing** [comment]
とりあえず、作っておいてみました。
参考にしてください。

[http://enyakitakagaya.github.io/#!howto/github/handson.md](http://enyakitakagaya.github.io/#!howto/github/handson.md)

**Comment by ToruHagihara** [comment]
ありがとうございます！

> 特にワークショップをするときに必要になること

この部分は別ページですかね。どんな項目をイメージされてますか？

**Comment by MrBearing** [comment]
そうですね。
とりあえず第一報でできることを見せようと思いまして。

ワークショップで必要になりそうなところは
- issueの作り方とコミット時のコメントの仕方 (TODO管理に)
- Googleドライブ等のリソースの使い分け
- ブランチを切って分岐したりマージするやり方(資料やソースの編集上で必要になるので)
- 編集が競合した場合の解決の仕方
- 以前のバージョンへの戻し方

等を考えています。

**Comment by ToruHagihara** [comment]
ありがとうございます。　いいですね。
最初からブランチ開発はハードル高い気がするのでmaster一本の開発から慣れていくのもアリだと思います。
この辺りはソースコードとドキュメント作成でスタイルが変わってくるかもですね。

**Comment by ToruHagihara** [comment]
別issueにすることも検討しますが、
Mac版のSourceTreeがとても不安定で使いにくいため、私は公式の方を使っています。
公式の方はGitHubFlowに乗せることが前提の作りでこちらも一長一短です・・・

使い方の説明の時に一言説明が必要なことを備忘としてメモっておきます。
