### ISSUE TITLE
サイトジェネレータを導入する

### ISSUE THREAD

**Issue by MrBearing** [EnyaKitakagaya/EnyaKitakagaya.github.io#3]
Markdownを用いて記述の可能なサイトジェネレータを導入する。

**Comment by MrBearing** [comment]
候補
- MDWiki：ファイル置くだけ
- Jekyll：ruby製のCMS　ローカルにRuby導入必要
- Pelican：ローカルにpython導入が必要。動作させるだけなら、問題ないかも

**Comment by MrBearing** [comment]
追加選択肢
- Jekyll now CMSとして動作する。　ローカルにJekyllの導入の必要なし

使えそうだけど、さしあたってはMDWikiを導入してみます。
投稿の編集だけなら、Githubからファイルを編集すればできるので、
CMSを導入するほどでも無いと考えました。

使い勝手が悪いようならJekyllもしくはPelican等で再構築
どのCMSも.mdファイルを参照してコンテンツを作るので、
環境を変えても移行はそこまで面倒にはならないと思います。

**Comment by ToruHagihara** [comment]
リポジトリに標準で付いてくるWikiでは機能が足りないドキュメントを想定していますか？

あと、以前md文書でWS当日用ドキュメントを作成したのですが、写真などイメージファイルの管理が煩雑になってしまった記憶があります。
この辺りの管理が簡単になると嬉しい。

**Comment by MrBearing** [comment]
@ToruHagihara 
MDwikはGit標準のwikiよりは多彩に表現が可能です。
[MDwiki](http://dynalon.github.io/mdwiki/#!index.md)

また、MDwikiにはGimmicksという記法が追加されています。
文字色を変えたりyoutube等の動画も埋め込めたりするので、拡張はしやすいと思います。

画像の管理に関しては、うまい方法がMDwikiにはなさそうです。。
画像フォルダを作ってそこを参照する格好になりますね。。

参考
[AOSN](http://aosn.github.io/#!/event/1-0913camp.md)
写真はこんな感じに

[MDwiki – Markdownをコンテンツに使ったCMS/Wikiシステム](http://www.moongift.jp/2013/11/mdwiki-markdown%E3%82%92%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E3%81%AB%E4%BD%BF%E3%81%A3%E3%81%9Fcmswiki%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0/)　moongiftの記事

**Comment by ToruHagihara** [comment]
さすが早い！
なるほど、mdにしても画像などのリソースにしても、WYSWYGにはならないのが編集する人によっては最初のハードルになりそうですね。うまく回避できると良いのですが。

**Comment by MrBearing** [comment]
運用は開始できたので、クローズしますね。
