### ISSUE TITLE
WSリポジトリのフォルダ構成を検討する

### ISSUE THREAD

**Issue by ToruHagihara** [EnyaKitakagaya/EnyaKitakagaya.github.io#5]
TestForWSにフォルダ構成を作ってみる。
最低限、必要と思っているのは以下。他にアイデアありますか？
1. 当日資料（PDFやソースファイルなど）
2. 開発資料（回路図の画像ファイルやfzzファイル、その他当日資料PDFの元になるファイル群）
3. 事前準備（必要な購入パーツリスト、準備物リストなどのえんやメンバー向け資料）

**Comment by ToruHagihara** [comment]
２と３は同じフォルダでもいいかも。

１はそのままZip化して参加者がダウンロードできるようにするイメージです。

**Comment by MrBearing** [comment]
@ToruHagihara 　アサインしときましたので、よろしくお願いします。

**Comment by ToruHagihara** [comment]
２、３が入るとややこしくなるので、まずは本当の最小限でフォルダ例を構成しましたがどうでしょう？。

**Comment by MrBearing** [comment]
@ToruHagihara  
問題無いと思います。
とりあえずはこれをベースに運用していってもらう方向で進めて見ましょう。

**Comment by ToruHagihara** [comment]
@MrBearing 確認ありがとうございます。これでクローズします。
やりたいことがでてきたら新issueを作りましょう。
